### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by thecodeduchess** [GBGitUser/codecademy-capstone#4]
**Grade: Meets Expectations**

**Summary:** This was a great implementation of the project. First, I test your project by downloading it and viewing it in my own browser. Next, I go step by step with your page against the requirements.  It matches to my specs exactly. After nitpicking through it, I did not find anything that requires a re-do.The code was easily readable and met the required styling, class and ID naming. If you want to build onto this project, you could consider adding a border on some of the elements, changing the background color or use other various font colors. I see you added an additional font but it was not a dramatic change. Don't be afraid to experiment and make it your own. That's how you get an exceeding expectations grade. 

I hope you are enjoying your learning experience. You are certainly ready to move on to the next step!

**Comment by GBGitUser** [comment]
Great - thanks very much. I didn't realize that we could mess about with the look and feel. If i had realized then I would have messed about with the palette and the fonts a lot more. Thanks for reviewing - good to know I'm on the right track! :)
